DEF MORE_POKEMON EQU const_value
	const MIMIKYU    ; fc
	const LITWICK    ; fd
	const LAMPENT    ; fe
	const CHANDELURE ; ff
	const DRIFLOON   ; 100
	const DRIFBLIM   ; 101
	const SINISTEA   ; 102
	const POLTEAGEIST ; 103
	const MISMAGIUS  ; 104
	const SANDYGAST  ; 105
	const PALOSSAND  ; 106
	const ZORUA      ; 107
	const ZOROARK    ; 108
	const PHANTUMP   ; 109
	const TREVENANT  ; 10a
	const DREEPY     ; 10b
	const DRAKLOAK   ; 10c
	const DRAGAPULT  ; 10d
	const HONEDGE    ; 10e
	const DOUBLADE   ; 10f
	const AEGISLASH  ; 110
	const SNORUNT    ; 111
	const FROSLASS   ; 112
	const GREAVARD   ; 113
	const HOUNDSTONE ; 114
	const MARSHADOW  ; 115
	const ROTOM      ; 116
	const GOLETT     ; 117
	const GOLURK     ; 118
	const FRILLISH   ; 119
	const JELLICENT  ; 11a
	const PUMPKABOO  ; 11b
	const GOURGEIST  ; 11c
	const POLTCHAGEIST ; 11d
	const SINISTCHA  ; 11e
