DEF MORE_POKEMON EQU const_value
	const MIMIKYU    ; fc
	const LITWICK    ; fd
	const LAMPENT    ; fe
	const CHANDELURE ; ff
	const DRIFLOON   ; 100
	const DRIFBLIM   ; 101
	const SINISTEA   ; 102
	const POLTEAGEIST ; 103
	const MISMAGIUS  ; 104
	const SANDYGAST  ; 105
	const PALOSSAND  ; 106
