	tilepal 0, ROOF, BROWN, RED, GREEN, BROWN, BROWN, YELLOW, WATER         ; 0
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, RED, WATER, BROWN, GRAY, GRAY, WATER           ; 1
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, BROWN, BROWN, GREEN, GREEN, WATER, WATER           ; 2
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, WATER, WATER, WATER         ; 3
	tilepal 0, WATER, WATER, WATER, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, WATER, WATER, WATER, WATER       ; 4
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, WATER, BROWN, WATER, WATER       ; 5
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
