	dw MimikyuAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw SinisteaAnimation
	dw PolteageistAnimation
	dw MismagiusAnimation
	dw SandygastAnimation
	dw PalossandAnimation
