	dw MimikyuAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw SinisteaAnimation
	dw PolteageistAnimation
	dw MismagiusAnimation
	dw SandygastAnimation
	dw PalossandAnimation
	dw ZoruaAnimation
	dw ZoroarkAnimation
	dw PhantumpAnimation
	dw TrevenantAnimation
	dw DreepyAnimation
	dw DrakloakAnimation
	dw DragapultAnimation
	dw HonedgeAnimation
	dw DoubladeAnimation
	dw AegislashAnimation
	dw SnoruntAnimation
	dw FroslassAnimation
	dw GreavardAnimation
	dw HoundstoneAnimation
	dw MarshadowAnimation
	dw RotomAnimation
	dw GolettAnimation
	dw GolurkAnimation
	dw FrillishAnimation
	dw JellicentAnimation
	dw PumpkabooAnimation
	dw GourgeistAnimation
	dw PoltchageistAnimation
	dw SinistchaAnimation
