MimikyuAnimation:    INCLUDE "gfx/pokemon/mimikyu/anim.asm"
LitwickAnimation:    INCLUDE "gfx/pokemon/litwick/anim.asm"
LampentAnimation:    INCLUDE "gfx/pokemon/lampent/anim.asm"
ChandelureAnimation: INCLUDE "gfx/pokemon/chandelure/anim.asm"
DrifloonAnimation:   INCLUDE "gfx/pokemon/drifloon/anim.asm"
DrifblimAnimation:   INCLUDE "gfx/pokemon/drifblim/anim.asm"
SinisteaAnimation:   INCLUDE "gfx/pokemon/sinistea/anim.asm"
PolteageistAnimation:INCLUDE "gfx/pokemon/polteageist/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
SandygastAnimation:  INCLUDE "gfx/pokemon/sandygast/anim.asm"
