MimikyuBitmasks:    INCLUDE "gfx/pokemon/mimikyu/bitmask.asm"
LitwickBitmasks:    INCLUDE "gfx/pokemon/litwick/bitmask.asm"
LampentBitmasks:    INCLUDE "gfx/pokemon/lampent/bitmask.asm"
ChandelureBitmasks: INCLUDE "gfx/pokemon/chandelure/bitmask.asm"
DrifloonBitmasks:   INCLUDE "gfx/pokemon/drifloon/bitmask.asm"
DrifblimBitmasks:   INCLUDE "gfx/pokemon/drifblim/bitmask.asm"
