	dw MimikyuBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw SinisteaBitmasks
	dw PolteageistBitmasks
	dw MismagiusBitmasks
	dw SandygastBitmasks
