	dw MimikyuBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw DrifloonBitmasks
	dw DrifblimBitmasks
	dw SinisteaBitmasks
	dw PolteageistBitmasks
	dw MismagiusBitmasks
	dw SandygastBitmasks
	dw PalossandBitmasks
	dw ZoruaBitmasks
	dw ZoroarkBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw DreepyBitmasks
	dw DrakloakBitmasks
	dw DragapultBitmasks
	dw HonedgeBitmasks
	dw DoubladeBitmasks
	dw AegislashBitmasks
	dw SnoruntBitmasks
	dw FroslassBitmasks
	dw GreavardBitmasks
	dw HoundstoneBitmasks
	dw MarshadowBitmasks
	dw RotomBitmasks
	dw GolettBitmasks
	dw GolurkBitmasks
	dw FrillishBitmasks
	dw JellicentBitmasks
	dw PumpkabooBitmasks
	dw GourgeistBitmasks
	dw PoltchageistBitmasks
	dw SinistchaBitmasks
