MimikyuAnimationIdle:    INCLUDE "gfx/pokemon/mimikyu/anim_idle.asm"
LitwickAnimationIdle:    INCLUDE "gfx/pokemon/litwick/anim_idle.asm"
LampentAnimationIdle:    INCLUDE "gfx/pokemon/lampent/anim_idle.asm"
ChandelureAnimationIdle: INCLUDE "gfx/pokemon/chandelure/anim_idle.asm"
DrifloonAnimationIdle:   INCLUDE "gfx/pokemon/drifloon/anim_idle.asm"
DrifblimAnimationIdle:   INCLUDE "gfx/pokemon/drifblim/anim_idle.asm"
