MimikyuAnimationIdle:    INCLUDE "gfx/pokemon/mimikyu/anim_idle.asm"
LitwickAnimationIdle:    INCLUDE "gfx/pokemon/litwick/anim_idle.asm"
LampentAnimationIdle:    INCLUDE "gfx/pokemon/lampent/anim_idle.asm"
ChandelureAnimationIdle: INCLUDE "gfx/pokemon/chandelure/anim_idle.asm"
DrifloonAnimationIdle:   INCLUDE "gfx/pokemon/drifloon/anim_idle.asm"
DrifblimAnimationIdle:   INCLUDE "gfx/pokemon/drifblim/anim_idle.asm"
SinisteaAnimationIdle:   INCLUDE "gfx/pokemon/sinistea/anim_idle.asm"
PolteageistAnimationIdle:INCLUDE "gfx/pokemon/polteageist/anim_idle.asm"
MismagiusAnimationIdle:  INCLUDE "gfx/pokemon/mismagius/anim_idle.asm"
SandygastAnimationIdle:  INCLUDE "gfx/pokemon/sandygast/anim_idle.asm"
PalossandAnimationIdle:  INCLUDE "gfx/pokemon/palossand/anim_idle.asm"
