MoreFrames: ; used only for BANK(MoreFrames)

MimikyuFrames:    INCLUDE "gfx/pokemon/mimikyu/frames.asm"
LitwickFrames:    INCLUDE "gfx/pokemon/litwick/frames.asm"
LampentFrames:    INCLUDE "gfx/pokemon/lampent/frames.asm"
ChandelureFrames: INCLUDE "gfx/pokemon/chandelure/frames.asm"
DrifloonFrames:   INCLUDE "gfx/pokemon/drifloon/frames.asm"
DrifblimFrames:   INCLUDE "gfx/pokemon/drifblim/frames.asm"
SinisteaFrames:   INCLUDE "gfx/pokemon/sinistea/frames.asm"
PolteageistFrames:INCLUDE "gfx/pokemon/polteageist/frames.asm"
MismagiusFrames:  INCLUDE "gfx/pokemon/mismagius/frames.asm"
SandygastFrames:  INCLUDE "gfx/pokemon/sandygast/frames.asm"
PalossandFrames:  INCLUDE "gfx/pokemon/palossand/frames.asm"
ZoruaFrames:      INCLUDE "gfx/pokemon/zorua/frames.asm"
ZoroarkFrames:    INCLUDE "gfx/pokemon/zoroark/frames.asm"
PhantumpFrames:   INCLUDE "gfx/pokemon/phantump/frames.asm"
TrevenantFrames:  INCLUDE "gfx/pokemon/trevenant/frames.asm"
DreepyFrames:     INCLUDE "gfx/pokemon/dreepy/frames.asm"
DrakloakFrames:   INCLUDE "gfx/pokemon/drakloak/frames.asm"
DragapultFrames:  INCLUDE "gfx/pokemon/dragapult/frames.asm"
HonedgeFrames:    INCLUDE "gfx/pokemon/honedge/frames.asm"
DoubladeFrames:   INCLUDE "gfx/pokemon/doublade/frames.asm"
AegislashFrames:  INCLUDE "gfx/pokemon/aegislash/frames.asm"
SnoruntFrames:    INCLUDE "gfx/pokemon/snorunt/frames.asm"
FroslassFrames:   INCLUDE "gfx/pokemon/froslass/frames.asm"
GreavardFrames:   INCLUDE "gfx/pokemon/greavard/frames.asm"
HoundstoneFrames: INCLUDE "gfx/pokemon/houndstone/frames.asm"
MarshadowFrames:  INCLUDE "gfx/pokemon/marshadow/frames.asm"
RotomFrames:      INCLUDE "gfx/pokemon/rotom/frames.asm"
GolettFrames:     INCLUDE "gfx/pokemon/golett/frames.asm"
GolurkFrames:     INCLUDE "gfx/pokemon/golurk/frames.asm"
FrillishFrames:   INCLUDE "gfx/pokemon/frillish/frames.asm"
JellicentFrames:  INCLUDE "gfx/pokemon/jellicent/frames.asm"
PumpkabooFrames:  INCLUDE "gfx/pokemon/pumpkaboo/frames.asm"
GourgeistFrames:  INCLUDE "gfx/pokemon/gourgeist/frames.asm"
PoltchageistFrames:INCLUDE "gfx/pokemon/poltchageist/frames.asm"
SinistchaFrames:  INCLUDE "gfx/pokemon/sinistcha/frames.asm"
