INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
INCBIN "gfx/footprints/misdreavus.1bpp"
